### ISSUE TITLE
Esphome compilation error after update from 2025.9 to 2025.11

### ISSUE THREAD

**Issue by pksoft585** [luar123/zigbee_esphome#70]
Hi,
I can't compile my project after update Esphome from 2025.9 to 2025.11. I got these errors:

```
INFO ESPHome 2025.11.0
INFO Reading configuration /config/esphome/xiao-esp32c6-01.yaml...
WARNING GPIO9 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Generating C++ source...
INFO Compiling app... Build path: /data/build/xiao-esp32c6-01
Processing xiao-esp32c6-01 (board: esp32-c6-devkitc-1; framework: espidf; platform: https://github.com/pioarduino/platform-espressif32/releases/download/55.03.31-2/platform-espressif32.zip)
--------------------------------------------------------------------------------
INFO Package configuration completed successfully
INFO Package configuration completed successfully
HARDWARE: ESP32C6 160MHz, 320KB RAM, 8MB Flash
 - contrib-piohome @ 3.4.4 
 - framework-espidf @ 3.50501.0 (5.5.1) 
 - tool-cmake @ 4.0.3 
 - tool-esp-rom-elfs @ 2024.10.11 
 - tool-esptoolpy @ 5.1.0 
 - tool-mklittlefs @ 3.2.0 
 - tool-ninja @ 1.13.1 
 - tool-scons @ 4.40801.0 (4.8.1) 
 - toolchain-riscv32-esp @ 14.2.0+20241119
Reading CMake configuration...
Dependency Graph
|-- noise-c @ 0.1.10
|-- ArduinoJson @ 7.4.2
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/api/api_connection.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/api/api_frame_helper.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/api/api_frame_helper_noise.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/api/api_pb2.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/api/api_pb2_service.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/api/api_server.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/api/list_entities.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/api/proto.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/api/subscribe_state.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/binary_sensor/automation.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/binary_sensor/binary_sensor.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/binary_sensor/filter.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/bmp085/bmp085.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/button/button.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/esp32/core.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/esp32/gpio.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/esp32/helpers.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/esp32/preferences.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/esphome/ota/ota_esphome.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/gpio/binary_sensor/gpio_binary_sensor.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/i2c/i2c.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/i2c/i2c_bus_esp_idf.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/json/json_util.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/logger/logger.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/logger/logger_esp32.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/logger/task_log_buffer.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/md5/md5.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/mdns/mdns_component.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/mdns/mdns_esp32.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/network/util.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/ota/ota_backend.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/ota/ota_backend_esp_idf.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/restart/switch/restart_switch.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/safe_mode/button/safe_mode_button.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/safe_mode/safe_mode.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/sensor/automation.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/sensor/filter.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/sensor/sensor.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/sha256/sha256.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/socket/bsd_sockets_impl.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/socket/socket.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/status/status_binary_sensor.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/switch/automation.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/switch/switch.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/template/binary_sensor/template_binary_sensor.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/template/switch/template_switch.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/time/automation.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/time/real_time_clock.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/uptime/sensor/uptime_seconds_sensor.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/uptime/sensor/uptime_timestamp_sensor.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/web_server/list_entities.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/web_server/web_server.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/web_server_base/web_server_base.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/web_server_idf/multipart.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/web_server_idf/utils.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/web_server_idf/web_server_idf.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/wifi/wifi_component.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/wifi/wifi_component_esp_idf.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/wifi_signal/wifi_signal_sensor.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/zigbee/automation.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/zigbee/time/zigbee_time.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/zigbee/zigbee.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/zigbee/zigbee_attribute.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/components/zigbee/zigbee_helpers.c.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/core/application.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/core/color.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/core/component.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/core/component_iterator.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/core/controller_registry.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/core/entity_base.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/core/helpers.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/core/log.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/core/ring_buffer.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/core/scheduler.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/core/time.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/esphome/core/util.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/src/main.cpp.o
Compiling .pioenvs/xiao-esp32c6-01/libfac/libsodium/crypto_onetimeauth/crypto_onetimeauth.o
Compiling .pioenvs/xiao-esp32c6-01/libfac/libsodium/crypto_onetimeauth/poly1305/donna/poly1305_donna.o
Compiling .pioenvs/xiao-esp32c6-01/libfac/libsodium/crypto_onetimeauth/poly1305/onetimeauth_poly1305.o
Compiling .pioenvs/xiao-esp32c6-01/libfac/libsodium/randombytes/internal/randombytes_internal_random.o
Compiling .pioenvs/xiao-esp32c6-01/libfac/libsodium/randombytes/randombytes.o
Compiling .pioenvs/xiao-esp32c6-01/libfac/libsodium/randombytes/sysrandom/randombytes_sysrandom.o
Compiling .pioenvs/xiao-esp32c6-01/libfac/libsodium/sodium/codecs.o
Compiling .pioenvs/xiao-esp32c6-01/libfac/libsodium/sodium/core.o
Compiling .pioenvs/xiao-esp32c6-01/libfac/libsodium/sodium/utils.o
Compiling .pioenvs/xiao-esp32c6-01/lib9e7/noise-c/backend/sodium/cipher-aesgcm.o
Compiling .pioenvs/xiao-esp32c6-01/lib9e7/noise-c/backend/sodium/cipher-chachapoly.o
Compiling .pioenvs/xiao-esp32c6-01/lib9e7/noise-c/backend/sodium/dh-curve25519.o
Compiling .pioenvs/xiao-esp32c6-01/lib9e7/noise-c/backend/sodium/hash-blake2b.o
Compiling .pioenvs/xiao-esp32c6-01/lib9e7/noise-c/backend/sodium/hash-sha256.o
Compiling .pioenvs/xiao-esp32c6-01/lib9e7/noise-c/crypto/aes/rijndael-alg-fst.o
Compiling .pioenvs/xiao-esp32c6-01/lib9e7/noise-c/crypto/blake2/blake2b.o
Compiling .pioenvs/xiao-esp32c6-01/lib9e7/noise-c/crypto/blake2/blake2s.o
Compiling .pioenvs/xiao-esp32c6-01/lib9e7/noise-c/protocol/errors.o
Compiling .pioenvs/xiao-esp32c6-01/lib9e7/noise-c/protocol/rand_os.o
Compiling .pioenvs/xiao-esp32c6-01/lib9e7/noise-c/protocol/rand_sodium.o
Compiling .pioenvs/xiao-esp32c6-01/lib9e7/noise-c/protocol/randstate.o
Compiling .pioenvs/xiao-esp32c6-01/lib9e7/noise-c/protocol/util.o
Compiling .pioenvs/xiao-esp32c6-01/app_trace/app_trace.c.o
Compiling .pioenvs/xiao-esp32c6-01/app_trace/app_trace_util.c.o
Compiling .pioenvs/xiao-esp32c6-01/app_trace/host_file_io.c.o
Compiling .pioenvs/xiao-esp32c6-01/app_trace/port/port_uart.c.o
Compiling .pioenvs/xiao-esp32c6-01/app_update/esp_ota_ops.c.o
Compiling .pioenvs/xiao-esp32c6-01/app_update/esp_ota_app_desc.c.o
Compiling .pioenvs/xiao-esp32c6-01/bootloader_support/src/bootloader_common.c.o
Compiling .pioenvs/xiao-esp32c6-01/bootloader_support/src/bootloader_common_loader.c.o
Compiling .pioenvs/xiao-esp32c6-01/bootloader_support/src/bootloader_clock_init.c.o
Compiling .pioenvs/xiao-esp32c6-01/bootloader_support/src/bootloader_mem.c.o
Compiling .pioenvs/xiao-esp32c6-01/bootloader_support/src/bootloader_random.c.o
Compiling .pioenvs/xiao-esp32c6-01/bootloader_support/src/bootloader_efuse.c.o
Compiling .pioenvs/xiao-esp32c6-01/bootloader_support/src/flash_encrypt.c.o
Compiling .pioenvs/xiao-esp32c6-01/bootloader_support/src/secure_boot.c.o
Compiling .pioenvs/xiao-esp32c6-01/bootloader_support/src/bootloader_random_esp32c6.c.o
Compiling .pioenvs/xiao-esp32c6-01/bootloader_support/bootloader_flash/src/bootloader_flash.c.o
Compiling .pioenvs/xiao-esp32c6-01/bootloader_support/bootloader_flash/src/flash_qio_mode.c.o
Compiling .pioenvs/xiao-esp32c6-01/bootloader_support/bootloader_flash/src/bootloader_flash_config_esp32c6.c.o
In file included from src/esphome.h:79,
                 from src/main.cpp:3:
src/esphome/components/zigbee/automation.h: In instantiation of 'class esphome::zigbee::SetAttrAction<short int, float>':
/config/esphome/xiao-esp32c6-01.yaml:405:97:   required from here
src/esphome/components/zigbee/automation.h:44:8: error: 'void esphome::zigbee::SetAttrAction<T, Ts>::play(Ts ...) [with T = short int; Ts = {float}]' marked 'override', but does not override
   44 |   void play(Ts... x) override { this->parent_->set_attr(this->value_.value(x...)); }
      |        ^~~~
/config/esphome/xiao-esp32c6-01.yaml: In function 'void setup()':
/config/esphome/xiao-esp32c6-01.yaml:405:97: error: invalid new-expression of abstract class type 'esphome::zigbee::SetAttrAction<short int, float>'
src/esphome/components/zigbee/automation.h:39:44: note:   because the following virtual functions are pure within 'esphome::zigbee::SetAttrAction<short int, float>':
   39 | template<typename T, typename... Ts> class SetAttrAction : public Action<Ts...> {
      |                                            ^~~~~~~~~~~~~
In file included from src/esphome/components/binary_sensor/filter.h:3,
                 from src/esphome/components/binary_sensor/binary_sensor.h:5,
                 from src/esphome/core/application.h:30,
                 from src/esphome/components/api/api_frame_helper.h:13,
                 from src/esphome/components/api/api_connection.h:5,
                 from src/esphome.h:3:
src/esphome/core/automation.h:225:16: note:     'void esphome::Action<Ts>::play(const Ts& ...) [with Ts = {float}]'
  225 |   virtual void play(const Ts &...x) = 0;
      |                ^~~~
Compiling .pioenvs/xiao-esp32c6-01/bootloader_support/src/bootloader_utility.c.o
Compiling .pioenvs/xiao-esp32c6-01/bootloader_support/src/flash_partitions.c.o
Compiling .pioenvs/xiao-esp32c6-01/bootloader_support/src/esp_image_format.c.o
Compiling .pioenvs/xiao-esp32c6-01/bootloader_support/src/bootloader_sha.c.o
Compiling .pioenvs/xiao-esp32c6-01/bootloader_support/src/esp32c6/secure_boot_secure_features.c.o
Compiling .pioenvs/xiao-esp32c6-01/cmock/CMock/src/cmock.c.o
Compiling .pioenvs/xiao-esp32c6-01/console/commands.c.o
Compiling .pioenvs/xiao-esp32c6-01/console/esp_console_common.c.o
Compiling .pioenvs/xiao-esp32c6-01/console/esp_console_repl_internal.c.o
Compiling .pioenvs/xiao-esp32c6-01/console/split_argv.c.o
Compiling .pioenvs/xiao-esp32c6-01/console/linenoise/linenoise.c.o
Compiling .pioenvs/xiao-esp32c6-01/console/esp_console_repl_chip.c.o
Compiling .pioenvs/xiao-esp32c6-01/console/argtable3/arg_cmd.c.o
Compiling .pioenvs/xiao-esp32c6-01/console/argtable3/arg_date.c.o
Compiling .pioenvs/xiao-esp32c6-01/console/argtable3/arg_dbl.c.o
Compiling .pioenvs/xiao-esp32c6-01/console/argtable3/arg_dstr.c.o
Compiling .pioenvs/xiao-esp32c6-01/console/argtable3/arg_end.c.o
*** [.pioenvs/xiao-esp32c6-01/src/main.cpp.o] Error 1
========================= [FAILED] Took 115.68 seconds =========================
```
This is my yaml:

```yaml
esphome:
  name: xiao-esp32c6-01
  friendly_name: Xiao C6 Zigbee
  on_boot:
    priority: 800  
    then:
      - if:
          condition:
             switch.is_on: xiao_esp32c6_01_wifi_onoff
          then:
            - binary_sensor.template.publish:
                id: xiao_esp32c6_01_wifi_status
                state: ON
          else:
            - binary_sensor.template.publish:
                id: xiao_esp32c6_01_wifi_status
                state: OFF

external_components:
  - source: github://luar123/zigbee_esphome

esp32:
  board: esp32-c6-devkitc-1
  partitions: partitions_zb.csv
  framework:
    type: esp-idf

# Enable logging
logger:
  hardware_uart: UART0

# Enable Home Assistant API
api:
  encryption:
    key: "==key=="
  reboot_timeout: 0s

ota:
  platform: esphome
  password: !secret esphome_ota_password

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  
i2c:
  sda: GPIO22
  scl: GPIO23
  scan: true
  id: bus_a

web_server:
  port: 80
  log: off
  version: 3
  local: true

globals:
  - id: time_sync
    type: bool
    restore_value: no
    initial_value: "false"

binary_sensor:
  - platform: status
    name: "Status"
    id: xiao_esp32c6_01_status
    icon: mdi:check-circle-outline
  - platform: gpio
    pin:
      number: 9
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Zigbee button"
    id: xiao_esp32c6_01_zigbee_button
    internal: true
    on_press:
      then:
        - zigbee.report: zb
    on_click:
      min_length: 5s
      max_length: 20s
      then:
        - zigbee.reset: zb
  - platform: gpio
    pin:
      number: 21
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Wifi button"
    id: xiao_esp32c6_01_wifi_button
    internal: true
    on_press:
      - if:
          condition: wifi.enabled
          then:
            - logger.log: "Wifi off...(gp)"
            - wifi.disable
          else:
            - logger.log: "Wifi on...(gp)"
            - wifi.enable
  - platform: template
    name: "Wifi stav" 
    id: xiao_esp32c6_01_wifi_status
    icon: mdi:wifi

switch:
# Restart
  - platform: restart
    name: "Restart"
    id: xiao_esp32c6_01_restart_switch
# Wifi on/off
  - platform: template
    name: "Wifi on/off"
    id: xiao_esp32c6_01_wifi_onoff
    icon: mdi:wifi
    internal: true
    optimistic: true
    restore_mode: ALWAYS_ON
    turn_off_action:
      - logger.log: "Wifi off...(bt)"
      - wifi.disable:
    turn_on_action:
      - logger.log: "Wifi on...(bt)"
      - wifi.enable:

button:
# Safe Mode
  - platform: safe_mode
    name: "Restart (Safe Mode)"
    entity_category: config
    id: xiao_esp32c6_01_safe_mode_switch
# ZB Reset    
  - platform: template
    name: "Zigbee reset"
    id: xiao_esp32c6_01_zb_reset
    icon: mdi:zigbee
    on_press:
      then:
        - zigbee.reset: zb
# ZB Report    
  - platform: template
    name: "Zigbee report"
    id: xiao_esp32c6_01_zb_report
    icon: mdi:zigbee
    on_press:
      then:
        - zigbee.report: zb

sensor:
  - platform: wifi_signal
    name: "WiFi signal"
    id: xiao_esp32c6_01_wifi
    icon: mdi:wifi
    update_interval: 60s
  - platform: uptime
    name: "Uptime"
    update_interval: 15s
    id: xiao_esp32c6_01_uptime

  # BMP180
  - platform: bmp085
    i2c_id: bus_a
    address: 0x77
    update_interval: 30s
    temperature:
      name: "Teplota"
      id: xiao_esp32c6_01_temp
      icon: mdi:thermometer
      unit_of_measurement: "°C"
      filters:
      - filter_out: 0.0
      - median:
          window_size: 3
          send_every: 3
          send_first_at: 1
    pressure:
      name: "Tlak"
      id: xiao_esp32c6_01_pressure
      icon: mdi:gauge
      unit_of_measurement: "hPa"
      filters:
      - filter_out: nan
      - lambda: >-
          return x / powf(1.0 - (210 / 44330.0), 5.255);
      on_value:
        then:
          - zigbee.setAttr:
              id: xiao_esp32c6_01_press_attr
              value: !lambda 'return (int)round(x * 10.0);'

zigbee:
  id: "zb"
  router: true
  power_supply: 1
  endpoints:
    - num: 1
      device_type: SIMPLE_SENSOR
      clusters:
#        - id: BASIC
#          attributes:
#            - attribute_id: 0x07   # Power Source
#              type: 8BIT_ENUM
#              value: 0x01          # 0x01 = Mains (power supply)
        - id: PRESSURE_MEASUREMENT
          attributes:
            - attribute_id: 0x0
              id: xiao_esp32c6_01_press_attr
              type: S16
              report: true
              value: 10000
              scale: 1
        - id: TEMP_MEASUREMENT
          attributes:
            - attribute_id: 0x0
              id: xiao_esp32c6_01_temp_attr
              type: S16
              report: true
              value: 100
              scale: 100
              device: xiao_esp32c6_01_temp
        - id: ON_OFF
          attributes:
            - attribute_id: 0x0
              id: xiao_esp32c6_01_wifi_state_attr
              type: U8
              report: true
              value: 1
              scale: 1
    - num: 2
      device_type: ON_OFF_LIGHT
      clusters:
        - id: ON_OFF
          attributes:
            - attribute_id: 0x0
              id: xiao_esp32c6_01_wifi_switch_attr
              type: BOOL
              report: true
              on_value:
                then:
                  - if:
                      condition: 
                        lambda: 'return (bool)x;'
                      then:
                        - switch.turn_off: xiao_esp32c6_01_wifi_onoff
                      else:
                        - switch.turn_on: xiao_esp32c6_01_wifi_onoff
  on_join:
    then:
      - logger.log: "Joined zigbee network..."

time:
  - platform: zigbee
    timezone: Europe/Prague
    id: xiao_esp32c6_01_time
    on_time_sync:
      then:
        - logger.log: "System clock synchronized..."
        - globals.set:
            id: time_sync
            value: "true"
    on_time:
      - seconds: /10
        then:
          - if:
              condition:
                lambda: 'return id(time_sync);'
              then:
                - logger.log: "Timer action (every 10 seconds)..."
                - zigbee.report: zb
                - if:
                    condition: wifi.enabled
                    then:
                      - logger.log: "WiFi is on..."
                      - zigbee.setAttr:
                          id: xiao_esp32c6_01_wifi_state_attr
                          value: !lambda 'return int(1);'
                      - binary_sensor.template.publish:
                          id: xiao_esp32c6_01_wifi_status
                          state: ON
                    else:
                      - logger.log: "WiFi is off..."
                      - zigbee.setAttr:
                          id: xiao_esp32c6_01_wifi_state_attr
                          value: !lambda 'return int(0);'
                      - binary_sensor.template.publish:
                          id: xiao_esp32c6_01_wifi_status
                          state: OFF
```

When I try older version (zigbee_esphome@e6b442fec22590d14c7293c20e7e651f45d75373) on local site with these modification

```python
//  void play(Ts... x) override { this->parent_->set_attr(this->value_.value(x...)); }
  void play(const Ts&... x) override { this->parent_->set_attr(this->value_.value(x...)); }
```
compilation was succesful, but I got error from linker...

I'm little bit lost... Thank you.

**Comment by luar123** [comment]
Thanks for reporting. Your fix seems correct, but you have to use the latest version (there was another breaking change I fixed already):
https://developers.esphome.io/blog/2025/11/06/action-framework-performance-optimization/

**Comment by pksoft585** [comment]
Yes, you are right! This fix with your latest version works.
Thank you very much.
BR
Petr

**Comment by pksoft585** [comment]
There is a problem with macro which tests Esphome version. It is necessary to add next definition (_#include "esphome/core/version.h"_) to the top of header file **_automation.h_** because macro at time of compilation doesn't know about Esphome version and uses wrong lines for compilation. Suggested start of file:

```c++
#pragma once

//#include <stdfloat> //deactive because not working with esp-idf 5.1.4

#include "esphome/core/component.h"
#include "esphome/core/automation.h"
#include "esphome/core/version.h"
...
```
